services:
# Redis Configuration
    redisserver:
        image: redis:7.2
        container_name: RedisContainer
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - ../RedisConfiguration/redis.conf:/usr/local/etc/redis/redis.conf
            - ../RedisConfiguration/users.acl:/usr/local/etc/redis/users.acl
            - redis-data:/data

        command: redis-server /usr/local/etc/redis/redis.conf

# Microservice Configuration    
    userservice:
        build: ./UserServiceGrpc
        container_name: UserServiceContainer
        ports:
            - "5001:5001"
    productservice:
        build: ./ProductServiceGrpc
        container_name: ProductServiceContainer
        ports:
            - "5002:5002"
    orderservice:
        build: ./OrderServiceGrpc
        container_name: OrderServiceContainer
        ports:
            - "5004:5004"
    apigateway:
        build: ./API Gateway
        container_name: APIGatewayContainer
        ports:
            - "5003:5003"
        depends_on:
            - userservice
            - productservice
            - orderservice
            - redisserver
# Volumes
volumes:
        redis-data:
#Network Configuration
networks:
  default:
    external: false
    name: ecom_services
    